(define + (native_function "list.inject {|sum, n| sum + n}"))
(define - (native_function "list.inject {|sum, n| sum - n}"))
(define * (native_function "list.inject {|sum, n| sum * n}"))
(define / (native_function "list.inject {|sum, n| sum / n}"))
(define = (native_function "!(list.map{|x| x == list[0]}).include?( false )"))
(define equal? (native_function "!(list.map{|x| x == list[0]}).include?( false )"))